export const PUBLIC_MCP_TOOL_BY_COMMAND = {
  consequences: "sustech_consequences",
  "calendar day": "sustech_calendar_day",
  "calendar terms": "sustech_calendar_terms",
  "online search": "sustech_online_search",
  "online talks list": "sustech_online_talks_list",
  "online talks search": "sustech_online_talks_search",
  "online talks get": "sustech_online_talks_get",
  "online manual list": "sustech_online_manual_list",
  "online manual get": "sustech_online_manual_get",
  "online contact search": "sustech_online_contact_search",
  "online contact get": "sustech_online_contact_get",
  "resources list": "sustech_resources_list",
  "resources search": "sustech_resources_search",
  "services status": "sustech_services_status",
  "papers search": "sustech_papers_search",
  "nces browse": "sustech_nces_browse",
  "nces filter-options": "sustech_nces_filter_options",
  "nces global-stats": "sustech_nces_global_stats",
  "nces rankings": "sustech_nces_rankings",
  "nces search": "sustech_nces_search",
  "nces by-code": "sustech_nces_by_code",
  "nces course": "sustech_nces_course",
  "nces reviews": "sustech_nces_reviews",
  "nces teacher": "sustech_nces_teacher",
  "nces stats": "sustech_nces_stats",
  "library search": "sustech_library_search",
  "library detail": "sustech_library_detail",
  "library search-url": "sustech_library_search_url",
  "faculty departments": "sustech_faculty_departments",
  "faculty list": "sustech_faculty_list",
  "faculty get": "sustech_faculty_get",
  "faculty search": "sustech_faculty_search",
  "faculty render": "sustech_faculty_render",
  "transit facilities": "sustech_transit_facilities",
  "transit find": "sustech_transit_find",
  "transit lines": "sustech_transit_lines",
  "transit schedule": "sustech_transit_schedule",
  "transit stops": "sustech_transit_stops",
  "transit live": "sustech_transit_live",
} as const;

export type PublicMcpExposedCommand = keyof typeof PUBLIC_MCP_TOOL_BY_COMMAND;
