export type CapabilityKind = "local" | "read" | "plan" | "mutation";

export interface Capability {
  command: string;
  summary: string;
  kind: CapabilityKind;
  network: boolean;
  authentication: "none" | "selected-service" | "sustech-cas" | "tis" | "bb" | "lib-booking" | "booking" | "ws" | "pms" | "nces" | "browser";
  confirmation: "none" | "required";
  status: "stable" | "preview";
}

export const CAPABILITIES: readonly Capability[] = [
  capability("version", "Show CLI and runtime versions.", "local"),
  capability("capabilities", "List the machine-discoverable command surface.", "local"),
  capability("describe", "Describe one installed command's exact usage, options, capability, and consequences.", "local"),
  capability("consequences", "List structured risks and verification rules for real-state mutations.", "local"),
  capability("doctor", "Inspect runtime, credential storage, and optional live service authentication without mutating remote state.", "read", { authentication: "selected-service", status: "preview" }),
  capability("calendar terms", "Read semester boundaries from the public academic-calendar dataset.", "read"),
  capability("calendar day", "Resolve a date into teaching week, holiday, makeup, and exam flags.", "read"),
  capability("faculty departments", "List the known public faculty departments.", "read", { network: false }),
  capability("faculty list", "List public faculty profiles in one department.", "read", { status: "preview" }),
  capability("faculty get", "Read one public faculty profile.", "read", { status: "preview" }),
  capability("faculty search", "Search public faculty profile fields.", "read", { status: "preview" }),
  capability("faculty render", "Render a public faculty profile as Agent-readable Markdown.", "read", { status: "preview" }),
  capability("online search", "Search selected public community-maintained SUSTech Online content with source and freshness metadata.", "read", { status: "preview" }),
  capability("online talks list", "List public SUSTech talks indexed by the community-maintained SUSTech Online repository.", "read", { status: "preview" }),
  capability("online talks search", "Search public SUSTech talks indexed by the community-maintained SUSTech Online repository.", "read", { status: "preview" }),
  capability("online talks get", "Read one exact public SUSTech talk with community-source provenance.", "read", { status: "preview" }),
  capability("online contact search", "Search institutional public contacts selected from the community-maintained SUSTech Online repository.", "read", { status: "preview" }),
  capability("online contact get", "Read one exact institutional public contact with community-source provenance.", "read", { status: "preview" }),
  capability("context", "Compose a truthful current-date snapshot and optional live academic context with per-source availability.", "read", { status: "preview" }),
  capability("profile show", "Read a whitelisted student-profile summary with independent source statuses instead of raw upstream payloads.", "read", { authentication: "sustech-cas", status: "preview" }),
  capability("profile export", "Export the whitelisted student-profile report as versioned local JSON at an explicit guarded destination.", "mutation", { authentication: "sustech-cas", status: "preview" }),
  capability("academic snapshot save", "Save versioned TIS state and optional Blackboard deadlines to an explicit guarded local file.", "mutation", { authentication: "sustech-cas", status: "preview" }),
  capability("academic snapshot diff", "Compare two verified academic snapshots locally without contacting campus services.", "local", { network: false, status: "preview" }),
  capability("academic changes", "Summarize semantic academic changes between two verified snapshots without contacting campus services.", "local", { network: false, status: "preview" }),
  capability("academic watch", "Capture one read-only academic snapshot, compare it with a guarded local baseline, and update that baseline only when at least one source is safely comparable.", "mutation", { authentication: "sustech-cas", status: "preview" }),
  capability("resources list", "List the built-in campus resource registry.", "read", { network: false }),
  capability("resources search", "Search the built-in campus resource registry.", "read", { network: false }),
  capability("wifi status", "Read the current macOS Wi-Fi association.", "read", { network: false }),
  capability("wifi events", "Read recent macOS SUSTC Wi-Fi events.", "read", { network: false }),
  capability("services status", "Report implemented, adapter-required, and unavailable service layers.", "local"),
  capability("papers search", "Search public CrossRef metadata with optional Unpaywall resolution.", "read"),
  capability("papers fetch-oa", "Download one Unpaywall-resolved OA PDF to an explicit guarded destination.", "mutation", { status: "preview" }),
  capability("nces browse", "Browse public NCES community course evaluations.", "read", { status: "preview" }),
  capability("nces search", "Search public NCES courses and review samples.", "read", { status: "preview" }),
  capability("nces course", "Read one public NCES course and its reviews.", "read", { status: "preview" }),
  capability("bb user", "Read the authenticated Blackboard user profile.", "read", { authentication: "bb", status: "preview" }),
  capability("bb courses", "List the authenticated user's Blackboard courses.", "read", { authentication: "bb", status: "preview" }),
  capability("bb content", "List Blackboard content items for one course or folder.", "read", { authentication: "bb", status: "preview" }),
  capability("bb attachments", "List teacher-provided files attached to one Blackboard content item.", "read", { authentication: "bb", status: "preview" }),
  capability("bb download", "Download one explicitly selected Blackboard content attachment to a local path.", "mutation", { authentication: "bb", status: "preview" }),
  capability("bb assignments", "List Blackboard gradebook assignment columns.", "read", { authentication: "bb", status: "preview" }),
  capability("bb deadlines", "Aggregate upcoming Blackboard assignment deadlines across accessible courses.", "read", { authentication: "bb", status: "preview" }),
  capability("bb calendar", "Read authenticated Blackboard calendar items with optional date, type, and course filters.", "read", { authentication: "bb", status: "preview" }),
  capability("bb calendar-link set", "Validate and save a native Blackboard calendar subscription link in the operating-system credential store using stdin.", "mutation", { status: "preview" }),
  capability("bb calendar-link show", "Inspect a stored Blackboard calendar subscription link, masked unless explicitly revealed.", "local", { network: false, status: "preview" }),
  capability("bb calendar-link fetch", "Fetch a stored native Blackboard calendar feed and optionally write it to an explicit guarded destination.", "mutation", { status: "preview" }),
  capability("bb calendar-link delete", "Delete one stored Blackboard calendar subscription link from the operating-system credential store.", "mutation", { network: false, status: "preview" }),
  capability("bb search", "Search Blackboard course content and matching attachment names across accessible courses.", "read", { authentication: "bb", status: "preview" }),
  capability("bb sync", "Sync teacher-provided Blackboard attachments into an explicit local directory.", "mutation", { authentication: "bb", status: "preview" }),
  capability("bb attempts", "List the authenticated student's Blackboard attempts for one assignment.", "read", { authentication: "bb", status: "preview" }),
  capability("bb submit preview", "Run authenticated read-only checks and bind a Blackboard submission plan to a file hash.", "plan", { authentication: "bb", status: "preview" }),
  capability("bb submit apply", "Upload and submit a Blackboard assignment attempt.", "mutation", { authentication: "bb", confirmation: "required", status: "preview" }),
  capability("ws programs", "List or search authenticated SUSTech Global programs.", "read", { authentication: "ws", status: "preview" }),
  capability("ws detail", "Read one authenticated SUSTech Global program detail.", "read", { authentication: "ws", status: "preview" }),
  capability("library search", "Search public Primo metadata through the normalized JSON path or an explicitly selected ephemeral browser session.", "read", { status: "preview" }),
  capability("library detail", "Read one exact-context Primo record through public JSON or an explicitly selected human-only browser path.", "read", { status: "preview" }),
  capability("library search-url", "Build a browser handoff URL for Primo without fabricating catalog results.", "plan", { network: false, status: "preview" }),
  capability("booking whoami", "Read a redacted eHall booking user profile after the CAS token handshake.", "read", { authentication: "booking", status: "preview" }),
  capability("booking rooms", "List and filter eHall campus rooms without creating a reservation.", "read", { authentication: "booking", status: "preview" }),
  capability("booking my-meetings", "List the authenticated user's current eHall bookings.", "read", { authentication: "booking", status: "preview" }),
  capability("booking create preview", "Run live inventory, exact room-calendar overlap checks, and policy checks for one intended eHall reservation target, then emit a confirmed apply handoff.", "plan", { authentication: "booking", status: "preview" }),
  capability("booking create apply", "Attempt one intended eHall room reservation after conservative live revalidation, then verify the exact outcome by read-back.", "mutation", { authentication: "booking", confirmation: "required", status: "preview" }),
  capability("booking cancel preview", "Run live read-only checks for one exact eHall meeting ID and emit a confirmed apply handoff.", "plan", { authentication: "booking", status: "preview" }),
  capability("booking cancel apply", "Cancel one exact eHall meeting after live revalidation.", "mutation", { authentication: "booking", confirmation: "required", status: "preview" }),
  capability("lib-booking whoami", "Read the authenticated IC library-booking user profile.", "read", { authentication: "lib-booking", status: "preview" }),
  capability("lib-booking home-summary", "Read idle library-room counts by category.", "read", { authentication: "lib-booking", status: "preview" }),
  capability("lib-booking labs", "List IC library-booking labs.", "read", { authentication: "lib-booking", status: "preview" }),
  capability("lib-booking rooms", "List IC library-booking rooms for an exact kind and lab.", "read", { authentication: "lib-booking", status: "preview" }),
  capability("lib-booking reservation-count", "Read the authenticated user's library reservation count.", "read", { authentication: "lib-booking", status: "preview" }),
  capability("lib-booking reservations", "List the authenticated user's library reservations in a date range.", "read", { authentication: "lib-booking", status: "preview" }),
  capability("lib-booking create preview", "Run live inventory, parseable reservation-window overlap checks, membership checks, and policy checks for one intended IC library reservation target, then emit a confirmed apply handoff.", "plan", { authentication: "lib-booking", status: "preview" }),
  capability("lib-booking create apply", "Attempt one intended IC library reservation after conservative live revalidation, then verify the exact outcome by read-back.", "mutation", { authentication: "lib-booking", confirmation: "required", status: "preview" }),
  capability("lib-booking cancel preview", "Run live read-only checks for one exact IC library reservation ID and emit a confirmed apply handoff.", "plan", { authentication: "lib-booking", status: "preview" }),
  capability("lib-booking cancel apply", "Cancel one exact IC library reservation after live revalidation.", "mutation", { authentication: "lib-booking", confirmation: "required", status: "preview" }),
  capability("pms check", "Verify direct PMS authentication without exposing session material.", "read", { authentication: "pms", status: "preview" }),
  capability("pms server-groups", "List PMS printer server groups.", "read", { authentication: "pms", status: "preview" }),
  capability("pms stations", "List and filter campus PMS printers.", "read", { authentication: "pms", status: "preview" }),
  capability("pms jobs", "List pending PMS print jobs without uploading or deleting files.", "read", { authentication: "pms", status: "preview" }),
  capability("pms scan-jobs", "List pending PMS scan jobs without deleting files.", "read", { authentication: "pms", status: "preview" }),
  capability("pms usage", "Read paginated PMS usage history for an exact date range.", "read", { authentication: "pms", status: "preview" }),
  capability("pms upload preview", "Validate one local file, read the current PMS queue, and build an exact upload apply command without uploading.", "plan", { authentication: "pms", status: "preview" }),
  capability("pms upload apply", "Upload one exact local file to the PMS print queue after live revalidation and SHA-256 confirmation.", "mutation", { authentication: "pms", confirmation: "required", status: "preview" }),
  capability("pms delete preview", "Read the current PMS print queue and build an exact delete apply command for one queued job.", "plan", { authentication: "pms", status: "preview" }),
  capability("pms delete apply", "Delete one exact queued PMS print job after live revalidation.", "mutation", { authentication: "pms", confirmation: "required", status: "preview" }),
  capability("auth login", "Verify credentials and save them in the operating-system credential store.", "mutation", { status: "preview" }),
  capability("auth status", "Inspect credential-profile and system-store availability without exposing secrets.", "local", { status: "preview" }),
  capability("auth logout", "Delete one local credential profile from the operating-system credential store.", "mutation", { network: false, status: "preview" }),
  capability("auth check", "Verify credentials against TIS, Blackboard, WS, booking, lib-booking (library-booking alias), or PMS.", "read", { authentication: "selected-service", status: "preview" }),
  capability("tis courses search", "Search the campus-wide course catalog.", "read", { authentication: "tis", status: "preview" }),
  capability("tis courses available", "Search courses available to the authenticated student.", "read", { authentication: "tis", status: "preview" }),
  capability("tis enrolled", "Read the normalized enrolled-course schedule.", "read", { authentication: "tis", status: "preview" }),
  capability("tis schedule", "Read a week or full semester personal schedule.", "read", { authentication: "tis", status: "preview" }),
  capability("tis grades", "Read normalized grades and calculate GPA.", "read", { authentication: "tis", status: "preview" }),
  capability("tis exams", "Read the current published exam schedule.", "read", { authentication: "tis", status: "preview" }),
  capability("tis plan init", "Create or replace a local persistent timetable-planning file with optional scoring preferences.", "local", { network: false, status: "preview" }),
  capability("tis plan show", "Inspect the local persistent timetable-planning file.", "local", { network: false, status: "preview" }),
  capability("tis plan add", "Add course codes, blocked periods, or scoring preferences to the local persistent timetable plan.", "local", { network: false, status: "preview" }),
  capability("tis plan remove", "Remove course codes or blocked periods from the local persistent timetable plan.", "local", { network: false, status: "preview" }),
  capability("tis plan solve", "Solve a saved local timetable plan against the live catalog with stored scored-ranking preferences.", "plan", { authentication: "tis", status: "preview" }),
  capability("tis plan explain", "Explain one exact course code or RWH using live selectable sections, the saved timetable plan, conservative degree-gap evidence, and community NCES signals.", "plan", { authentication: "tis", status: "preview" }),
  capability("tis plan recommend", "Rank explicitly requested or saved-plan course sections using live availability while keeping degree and community evidence source-labelled.", "plan", { authentication: "tis", status: "preview" }),
  capability("tis classroom rooms", "Build a classroom directory from the campus course catalog.", "read", { authentication: "tis", status: "preview" }),
  capability("tis classroom occupancy", "Query catalogued classroom occupancy for an exact period.", "read", { authentication: "tis", status: "preview" }),
  capability("tis classroom free", "Find classrooms without a catalogued class in an exact period.", "read", { authentication: "tis", status: "preview" }),
  capability("tis classroom live", "Read a room's live TIS classroom schedule, including borrowings not present in the public catalog.", "read", { authentication: "tis", status: "preview" }),
  capability("tis classroom now", "Read a room's live TIS occupancy for the current Shenzhen teaching period.", "read", { authentication: "tis", status: "preview" }),
  capability("tis evals", "Read teaching-evaluation task status without submitting answers.", "read", { authentication: "tis", status: "preview" }),
  capability("tis ical", "Read TIS, Blackboard, and academic-calendar sources, then optionally write a guarded local iCalendar file to an explicit destination.", "mutation", { authentication: "selected-service", status: "preview" }),
  capability("tis timetable", "Solve non-conflicting section combinations locally after catalog fetch.", "plan", { authentication: "tis", status: "preview" }),
  capability("tis degree progress", "Read the authenticated student's TIS-reported cultivation-plan credits, category constraints, module gaps, and optional course details.", "read", { authentication: "tis", status: "preview" }),
  capability("tis degree missing", "Derive a conservative graduation-gap report from TIS degree progress, grade history, and current enrolled courses.", "plan", { authentication: "tis", status: "preview" }),
  capability("tis degree audit", "Audit live grade records against a local JSON requirement file without auto-resolving ambiguous matches.", "plan", { authentication: "tis", status: "preview" }),
  capability("tis enroll preview", "Build an exact enrollment action without network or mutation.", "plan", { network: false, status: "preview" }),
  capability("tis selection preview", "Build typed enroll, drop, cart, or bid payloads without sending them, with optional exact RWH handoff for apply.", "plan", { network: false, status: "preview" }),
  capability("tis selection reconcile", "Poll an exact courseId/RWH/round target after an uncertain selection write without repeating the mutation.", "read", { authentication: "tis", status: "preview" }),
  capability("tis selection apply", "Submit an exact cart, drop, or bid mutation to TIS after live revalidation.", "mutation", { authentication: "tis", confirmation: "required", status: "preview" }),
  capability("tis bid plan", "Validate a multi-course bid budget and build local write previews.", "plan", { network: false, status: "preview" }),
  capability("tis bid apply", "Submit exact multi-course bid updates to TIS after live revalidation.", "mutation", { authentication: "tis", confirmation: "required", status: "preview" }),
  capability("tis enroll apply", "Submit an enrollment action to TIS.", "mutation", { authentication: "tis", confirmation: "required", status: "preview" }),
  capability("transit facilities", "List public campus buildings and gates.", "read"),
  capability("transit find", "Search public campus facilities and bus stops.", "read"),
  capability("transit lines", "List public bus routes for workdays or holidays.", "read"),
  capability("transit schedule", "Read departures for a public bus route.", "read"),
  capability("transit stops", "List public stops for a live bus route.", "read"),
  capability("transit live", "Read public live bus positions.", "read"),
] as const;

function capability(
  command: string,
  summary: string,
  kind: CapabilityKind,
  overrides: Partial<Omit<Capability, "command" | "summary" | "kind">> = {},
): Capability {
  return {
    command,
    summary,
    kind,
    network: kind === "read" || kind === "mutation" || kind === "plan",
    authentication: "none",
    confirmation: "none",
    status: "stable",
    ...overrides,
  };
}

export function formatCapabilities(capabilities: readonly Capability[]): string {
  const groups = new Map<CapabilityKind, Capability[]>();
  for (const entry of capabilities) groups.set(entry.kind, [...(groups.get(entry.kind) ?? []), entry]);
  const sections = (["local", "read", "plan", "mutation"] as const)
    .filter((kind) => groups.has(kind))
    .map((kind) => [
      kind.toUpperCase(),
      ...(groups.get(kind) ?? []).map((entry) => {
        const flags = [
          entry.authentication !== "none" ? `auth:${entry.authentication}` : "",
          entry.confirmation === "required" ? "confirmation:required" : "",
          entry.network ? "network" : "local",
          entry.status === "preview" ? "preview" : "",
        ].filter(Boolean).join(", ");
        return `  ${entry.command}\n    ${entry.summary} [${flags}]`;
      }),
    ].join("\n"));
  return `Capabilities · schema version 1\n\n${sections.join("\n\n")}`;
}
