export const CLI_PARSE_OPTIONS = {
  semester: { type: "string" },
  limit: { type: "string" },
  refresh: { type: "boolean", default: false },
  round: { type: "string" },
  "credentials-file": { type: "string" },
  "course-id": { type: "string" },
  rwh: { type: "string" },
  bid: { type: "string" },
  confirm: { type: "boolean", default: false },
  week: { type: "string" },
  all: { type: "boolean", default: false },
  max: { type: "string" },
  block: { type: "string", multiple: true },
  day: { type: "string" },
  direction: { type: "string" },
  "route-index": { type: "string" },
  status: { type: "string" },
  "content-id": { type: "string" },
  "column-id": { type: "string" },
  file: { type: "string" },
  comment: { type: "string" },
  "expected-sha256": { type: "string" },
  destination: { type: "string" },
  state: { type: "string" },
  overwrite: { type: "boolean", default: false },
  days: { type: "string" },
  course: { type: "string" },
  kind: { type: "string" },
  attachments: { type: "string" },
  live: { type: "boolean", default: false },
  "allow-late": { type: "boolean", default: false },
  "period-start": { type: "string" },
  "period-end": { type: "string" },
  "week-one-monday": { type: "string" },
  "teaching-start": { type: "string" },
  "calendar-name": { type: "string" },
  include: { type: "string", multiple: true },
  where: { type: "string" },
  pick: { type: "string", multiple: true },
  "bid-limit": { type: "string" },
  cultivation: { type: "string" },
  year: { type: "string" },
  "calendar-level": { type: "string" },
  date: { type: "string" },
  level: { type: "string" },
  department: { type: "string" },
  full: { type: "boolean", default: false },
  minutes: { type: "string" },
  category: { type: "string" },
  section: { type: "string" },
  page: { type: "string" },
  "page-size": { type: "string" },
  sort: { type: "string" },
  "min-year": { type: "string" },
  "open-access": { type: "boolean", default: false },
  "resolve-oa": { type: "boolean", default: false },
  "parent-id": { type: "string" },
  "program-code": { type: "string" },
  "program-token": { type: "string" },
  available: { type: "boolean", default: false },
  start: { type: "string" },
  end: { type: "string" },
  begin: { type: "string" },
  "kind-id": { type: "string" },
  "lab-id": { type: "string" },
  "class-kind": { type: "string" },
  "need-status": { type: "string" },
  "room-id": { type: "string" },
  "meeting-id": { type: "string" },
  title: { type: "string" },
  participants: { type: "string" },
  description: { type: "string" },
  "dev-id": { type: "string" },
  "member-kind": { type: "string" },
  member: { type: "string", multiple: true },
  memo: { type: "string" },
  "reservation-id": { type: "string" },
  "server-group": { type: "string" },
  type: { type: "string" },
  color: { type: "string" },
  paper: { type: "string" },
  duplex: { type: "string" },
  copies: { type: "string" },
  "page-from": { type: "string" },
  "page-to": { type: "string" },
  service: { type: "string" },
  profile: { type: "string" },
  sid: { type: "string" },
  "password-stdin": { type: "boolean", default: false },
  path: { type: "string" },
  requirements: { type: "string" },
  details: { type: "boolean", default: false },
  since: { type: "string" },
  until: { type: "string" },
  "url-stdin": { type: "boolean", default: false },
  reveal: { type: "boolean", default: false },
  "include-blackboard": { type: "boolean", default: false },
  browser: { type: "boolean", default: false },
  interactive: { type: "boolean", default: false },
  "early-period-threshold": { type: "string" },
  "weight-early-session": { type: "string" },
  "weight-gap-segment": { type: "string" },
  "weight-gap-period": { type: "string" },
  "weight-distinct-weekday": { type: "string" },
  "weight-campus-switch": { type: "string" },
  output: { type: "string" },
  json: { type: "boolean", default: false },
  jsonl: { type: "boolean", default: false },
  pretty: { type: "boolean", default: false },
  help: { type: "boolean", short: "h", default: false },
} as const;

export type CliOptionName = keyof typeof CLI_PARSE_OPTIONS;

export const SHARED_OUTPUT_OPTION_NAMES = ["output", "json", "jsonl", "pretty"] as const;

export const COMMAND_OPTIONS: Readonly<Record<string, readonly CliOptionName[]>> = {
  describe: [],
  "auth login": ["profile", "sid", "service", "password-stdin"],
  "auth status": ["profile"],
  "auth logout": ["profile"],
  "auth check": ["service", "credentials-file", "profile"],
  doctor: ["profile", "credentials-file", "service", "live"],
  "calendar terms": ["year", "calendar-level"],
  "calendar day": ["date", "calendar-level"],
  "academic snapshot save": ["credentials-file", "semester", "destination", "include-blackboard", "overwrite"],
  "academic snapshot diff": [],
  "academic changes": [],
  "academic watch": ["credentials-file", "semester", "state", "include-blackboard", "overwrite"],
  "faculty list": ["full", "limit"],
  "faculty search": ["department", "limit"],
  "online search": ["section", "since", "until", "limit"],
  "talks list": ["all"],
  "talks search": ["all"],
  "online talks list": ["since", "until", "limit"],
  "online talks search": ["since", "until", "limit"],
  "online talks get": [],
  "online contact search": ["limit"],
  "online contact get": [],
  context: ["date", "calendar-level", "level", "live", "credentials-file"],
  "profile show": ["credentials-file", "profile"],
  "profile export": ["credentials-file", "profile", "destination", "overwrite"],
  "resources list": ["category"],
  "resources search": ["category"],
  "wifi events": ["minutes"],
  "papers search": ["max", "min-year", "open-access", "resolve-oa"],
  "papers fetch-oa": ["destination", "overwrite"],
  "nces browse": ["page", "page-size", "sort"],
  "bb user": ["credentials-file"],
  "bb courses": ["credentials-file"],
  "bb content": ["credentials-file", "parent-id"],
  "bb attachments": ["credentials-file"],
  "bb download": ["credentials-file", "destination", "overwrite"],
  "bb assignments": ["credentials-file"],
  "bb deadlines": ["credentials-file", "days", "course"],
  "bb calendar": ["credentials-file", "course-id", "type", "since", "until"],
  "bb calendar-link set": ["profile", "url-stdin"],
  "bb calendar-link show": ["profile", "reveal"],
  "bb calendar-link fetch": ["profile", "destination", "overwrite"],
  "bb calendar-link delete": ["profile"],
  "bb search": ["credentials-file", "course", "kind", "attachments", "page", "page-size"],
  "bb sync": ["credentials-file", "content-id", "destination", "overwrite"],
  "bb attempts": ["credentials-file", "content-id", "column-id", "status"],
  "bb submit preview": ["credentials-file", "course-id", "content-id", "column-id", "file", "comment"],
  "bb submit apply": ["credentials-file", "course-id", "content-id", "column-id", "file", "expected-sha256", "comment", "allow-late", "confirm"],
  "ws programs": ["credentials-file", "page", "page-size"],
  "ws detail": ["credentials-file", "program-code", "program-token"],
  "library search": ["limit", "browser", "interactive"],
  "library detail": ["browser", "interactive"],
  "library search-url": ["limit"],
  "booking whoami": ["credentials-file"],
  "booking rooms": ["credentials-file", "available", "page", "page-size"],
  "booking my-meetings": ["credentials-file", "page", "page-size"],
  "booking create preview": ["credentials-file", "room-id", "start", "end", "title", "participants", "description"],
  "booking create apply": ["credentials-file", "room-id", "start", "end", "title", "participants", "description", "confirm"],
  "booking cancel preview": ["credentials-file", "meeting-id"],
  "booking cancel apply": ["credentials-file", "meeting-id", "confirm"],
  "lib-booking whoami": ["credentials-file"],
  "lib-booking home-summary": ["credentials-file"],
  "lib-booking labs": ["credentials-file", "class-kind"],
  "lib-booking rooms": ["credentials-file", "kind-id", "lab-id", "class-kind"],
  "lib-booking reservation-count": ["credentials-file"],
  "lib-booking reservations": ["credentials-file", "start", "end", "need-status", "page", "page-size"],
  "lib-booking create preview": ["credentials-file", "kind-id", "lab-id", "dev-id", "start", "end", "title", "class-kind", "member-kind", "member", "memo"],
  "lib-booking create apply": ["credentials-file", "kind-id", "lab-id", "dev-id", "start", "end", "title", "class-kind", "member-kind", "member", "memo", "confirm"],
  "lib-booking cancel preview": ["credentials-file", "reservation-id"],
  "lib-booking cancel apply": ["credentials-file", "reservation-id", "confirm"],
  "pms check": ["credentials-file"],
  "pms server-groups": ["credentials-file"],
  "pms stations": ["credentials-file", "server-group"],
  "pms jobs": ["credentials-file"],
  "pms scan-jobs": ["credentials-file"],
  "pms usage": ["credentials-file", "begin", "end", "type", "page", "page-size"],
  "pms upload preview": ["credentials-file", "file", "color", "paper", "duplex", "page-from", "page-to", "copies"],
  "pms upload apply": ["credentials-file", "file", "expected-sha256", "color", "paper", "duplex", "page-from", "page-to", "copies", "confirm"],
  "pms delete preview": ["credentials-file"],
  "pms delete apply": ["credentials-file", "confirm"],
  "tis courses search": ["credentials-file", "semester", "limit", "refresh"],
  "tis courses available": ["credentials-file", "semester", "limit", "round"],
  "tis enrolled": ["credentials-file", "semester"],
  "tis schedule": ["credentials-file", "semester", "week", "all"],
  "tis grades": ["credentials-file", "semester"],
  "tis exams": ["credentials-file"],
  "tis plan init": [
    "semester",
    "block",
    "path",
    "early-period-threshold",
    "weight-early-session",
    "weight-gap-segment",
    "weight-gap-period",
    "weight-distinct-weekday",
    "weight-campus-switch",
  ],
  "tis plan show": ["path"],
  "tis plan add": [
    "block",
    "path",
    "early-period-threshold",
    "weight-early-session",
    "weight-gap-segment",
    "weight-gap-period",
    "weight-distinct-weekday",
    "weight-campus-switch",
  ],
  "tis plan remove": ["block", "path"],
  "tis plan solve": ["credentials-file", "semester", "refresh", "max", "path"],
  "tis plan explain": ["credentials-file", "semester", "round", "path"],
  "tis plan recommend": ["credentials-file", "semester", "round", "path", "max"],
  "tis classroom rooms": ["credentials-file", "semester", "refresh"],
  "tis classroom occupancy": ["credentials-file", "semester", "refresh", "week", "day", "period-start", "period-end"],
  "tis classroom free": ["credentials-file", "semester", "refresh", "week", "day", "period-start", "period-end"],
  "tis classroom live": ["credentials-file", "semester"],
  "tis classroom now": ["credentials-file", "semester"],
  "tis evals": ["credentials-file", "semester", "status"],
  "tis ical": ["credentials-file", "semester", "week-one-monday", "teaching-start", "calendar-level", "calendar-name", "include", "destination", "overwrite"],
  "tis timetable": ["credentials-file", "semester", "refresh", "max", "block"],
  "tis degree audit": ["credentials-file", "semester", "requirements"],
  "tis degree progress": ["credentials-file", "details"],
  "tis degree missing": ["credentials-file", "semester"],
  "tis enroll preview": ["semester", "course-id", "rwh", "round", "bid"],
  "tis selection preview": ["semester", "course-id", "rwh", "round", "bid", "where", "cultivation"],
  "tis selection apply": ["credentials-file", "semester", "course-id", "rwh", "round", "bid", "where", "cultivation", "confirm"],
  "tis bid plan": ["semester", "pick", "bid-limit", "where", "round", "cultivation"],
  "tis bid apply": ["credentials-file", "semester", "pick", "where", "round", "cultivation", "confirm"],
  "tis enroll apply": ["credentials-file", "semester", "course-id", "rwh", "round", "bid", "confirm"],
  "transit find": ["limit"],
  "transit lines": ["day"],
  "transit schedule": ["route-index", "day"],
  "transit stops": ["direction"],
};
